[package]
name = "mypayment_module"
version = "0.0.0"

[addresses]
named_addr = "0x698ad948b44dffec3507403862d6de5832a37a3d16dd74a78090e84f65696bad"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "devnet"
subdir = "aptos-stdlib"
